FROM python:3.12.2-alpine3.19
LABEL maintainer="mrrahbarnia@gmail.com"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir app
WORKDIR /app

COPY ./requirements/local.txt /tmp/local.txt
COPY ./requirements/base.txt /tmp/base.txt
COPY ./app /app

RUN pip install --upgrade pip && \
    apk add --no-cache postgresql-client jpeg-dev && \
    apk add --no-cache --virtual .tmp-build-deps \
        build-base postgresql-dev musl-dev zlib zlib-dev linux-headers && \
    pip install --no-cache-dir -r /tmp/local.txt && \
    rm -rf /tmp && \
    apk del .tmp-build-deps && \
    adduser \
      --disabled-password \
      --no-create-home \
      mohammadreza && \
    mkdir -p /vol/web/static && \
    mkdir -p /vol/web/media && \
    chown -R mohammadreza:mohammadreza /vol && \
    chmod -R 700 /vol

USER mohammadreza
