version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/app/
    environment:
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=db
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db
    volumes:
      - dev-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=changeme

  redis:
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - redis-data:/data


volumes:
  dev-database:
  redis-data:
